# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import message_pb2 as message__pb2


class MessageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Stream = channel.unary_stream(
        '/Message/Stream',
        request_serializer=message__pb2.Request.SerializeToString,
        response_deserializer=message__pb2.Response.FromString,
        )


class MessageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Stream': grpc.unary_stream_rpc_method_handler(
          servicer.Stream,
          request_deserializer=message__pb2.Request.FromString,
          response_serializer=message__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Message', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
